import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { aggregateHabits, queryDataSource, runSync } from './sync-notion.mjs';
const habits = [{ name: 'Estudo', area: 'Concursos', status: 'Ativo', weeklyGoal: 5, targetMinutes: 30, plannedDays: ['Seg'] }, { name: 'Pausado', area: 'Pessoal', status: 'Pausado', weeklyGoal: null, targetMinutes: null, plannedDays: [] }];
const log = (date, result, duration = null, habitName = 'Estudo') => ({ date, result, duration, habitName });
const aggregate = logs => aggregateHabits(habits, logs, '2026-09-15T12:00:00.000Z');
const empty = aggregate([]);
assert.equal(empty.summary.activeHabits, 1); assert.equal(empty.summary.completionRate, null); assert.equal(empty.summary.currentStreak, 0); assert.deepEqual(empty.daily, []);
assert.equal(aggregate([log('2026-09-01', 'Feito', 30)]).summary.completionRate, 100);
assert.equal(aggregate([log('2026-09-01', 'Não feito')]).summary.completionRate, 0);
assert.equal(aggregate([log('2026-09-01', 'Pulado / não aplicável')]).summary.completionRate, null);
assert.equal(aggregate([log('2026-09-01', 'Feito'), log('2026-09-01', 'Não feito')]).daily[0].state, 'partial');
assert.equal(aggregate([log('2026-09-01', 'Feito', 10), log('2026-09-01', 'Feito', 20, 'Outro')]).daily[0].minutes, 30);
assert.equal(aggregate(Array.from({ length: 7 }, (_, i) => log(`2026-09-0${i + 1}`, 'Feito'))).summary.currentStreak, 7);
assert.equal(aggregate([log('2026-09-01', 'Feito'), log('2026-09-02', 'Não feito'), log('2026-09-03', 'Feito')]).summary.bestStreak, 1);
assert.equal(aggregate([log('2026-09-01', 'Feito', null)]).weekly[0].minutes, 0);
let calls = 0;
const paginatedFetch = async () => { calls++; return { ok: true, json: async () => calls === 1 ? { results: Array(100).fill({}), has_more: true, next_cursor: 'next' } : { results: [{}], has_more: false, next_cursor: null } }; };
assert.equal((await queryDataSource('source', { token: 'test-token', fetchImpl: paginatedFetch })).length, 101); assert.equal(calls, 2);
const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'notion-sync-')); const outputPath = path.join(tempDir, 'habits.json');
await fs.writeFile(outputPath, '{"valid":"previous"}\n');
await assert.rejects(runSync({ token: 'test-token', habitsDataSourceId: 'a', logsDataSourceId: 'b', outputPath, fetchImpl: async () => ({ ok: false, status: 503 }) }));
assert.equal(JSON.parse(await fs.readFile(outputPath, 'utf8')).valid, 'previous');
await fs.rm(tempDir, { recursive: true, force: true });
console.log('OK: 12 cenários de sincronização e agregação validados.');
